### ISSUE TITLE
bakery issue in version 2.0

### ISSUE THREAD

**Issue by schoekek** [seppovic/check_mk-plugins#17]
```
Exception: Error running automation call bake-agents (exit code 2), error: 

Error creating 0807f53b3979407f/linux_deb agent for host: Error in bakery plugin "slapd": 'bool' object is not iterable

Traceback (most recent call last):
  File "/omd/sites/test/lib/python/cmk_base/cee/agent_bakery.py", line 366, in execute_bakery_plugin
    bake_func(*func_args)
  File "/omd/sites/test/local/share/check_mk/agents/bakery/slapd", line 16, in bake_slapd
    for instance, instconf in conf:
TypeError: 'bool' object is not iterable
.
```

**Comment by seppovic** [comment]
Sorry i won't add cmk2.0 compatibility, i should have archived this repo some time ago.
