### ISSUE TITLE
No messages are sent

### ISSUE THREAD

**Issue by grego1981** [seppovic/check_mk-plugins#8]
Hello and a happy new year!

I'm testing the xmpp module for check_mk raw 1.4.19 and I have trouble getting the messages to appear. Below is the output of the debug notify.log. 

I'll be happy to send any additional info needed!

`2018-01-05 10:14:37   * notifying fylakio via xmpp.pl, parameters: xmppserver, debug, service_message, password, host_message, user, bulk: no
2018-01-05 10:14:37      executing /omd/sites/site/local/share/check_mk/notifications/xmpp.pl
2018-01-05 10:14:37      Output: D-main: xmpp notification handler start, got the following env_vars:
2018-01-05 10:14:37      Output: $VAR1 = {
2018-01-05 10:14:37      Output:           'SERVICEACKAUTHOR' => '',
2018-01-05 10:14:37      Output:           'NOTIFICATIONCOMMENT' => '',
2018-01-05 10:14:37      Output:           'HOSTOUTPUT' => 'OK - XX.XX.XX.XX: rta 0.154ms, lost 0%',
2018-01-05 10:14:37      Output:           'LASTHOSTUP_REL' => '0d 00:00:25',
2018-01-05 10:14:37      Output:           'LASTSERVICESTATECHANGE_REL' => '0d 00:00:01',
2018-01-05 10:14:37      Output:           'SERVICEOUTPUT' => 'UNKNOWN - check failed - please submit a crash report!',
2018-01-05 10:14:37      Output:           'SERVICE_SL' => '$_SERVICEEC_SL$',
2018-01-05 10:14:37      Output:           'SERVICEGROUPNAMES' => '',
2018-01-05 10:14:37      Output:           'PREVIOUSHOSTHARDSHORTSTATE' => 'UP',
2018-01-05 10:14:37      Output:           'HOSTPROBLEMID' => '0',
2018-01-05 10:14:37      Output:           'LASTSERVICEOK_REL' => '0d 00:01:02',
2018-01-05 10:14:37      Output:           'SERVICEFORURL' => 'SERVICE DESC',
2018-01-05 10:14:37      Output:           'NOTIFICATIONAUTHORALIAS' => '',
2018-01-05 10:14:37      Output:           'HOSTATTEMPT' => '1',
2018-01-05 10:14:37      Output:           'HOSTCHECKCOMMAND' => 'check-mk-host-ping!-w 200.00,80.00% -c 500.00,100.00%',
2018-01-05 10:14:37      Output:           'HOSTADDRESS' => 'X.X.X.X',
2018-01-05 10:14:37      Output:           'HOST_ADDRESS_6' => '',
2018-01-05 10:14:37      Output:           'SHORTDATETIME' => '2018-01-05 10:14:36',
2018-01-05 10:14:37      Output:           'CONTACTS' => 'Outside_contact,gtsms,afsms,omdadmin',
2018-01-05 10:14:37      Output:           'LASTSERVICEOK' => '1515140015',
2018-01-05 10:14:37      Output:           'LONGSERVICEOUTPUT' => 'aaaaaaaaa',
2018-01-05 10:14:37      Output:           'HOST_ADDRESS_4' => 'X.X.X.X',
2018-01-05 10:14:37      Output:           'DATE' => '2018-01-05',
2018-01-05 10:14:37      Output:           'SERVICEDESC' => 'Description of service',
2018-01-05 10:14:37      Output:           'MICROTIME' => '1515140077389183',
2018-01-05 10:14:37      Output:           'HOSTNAME' => 'host1',
2018-01-05 10:14:37      Output:           'HOSTNOTIFICATIONNUMBER' => '1',
2018-01-05 10:14:37      Output:           'PARAMETER_PASSWORD' => 'password',
2018-01-05 10:14:37      Output:           'HOSTPERFDATA' => 'rta=0.154ms;200.000;500.000;0; pl=0%;80;100;; rtmax=0.186ms;;;; rtmin=0.144ms;;;;',
2018-01-05 10:14:37      Output:           'LOGDIR' => '/omd/sites/site/var/check_mk/notify',
2018-01-05 10:14:37      Output:           'PREVIOUSSERVICEHARDSTATE' => 'OK',
2018-01-05 10:14:37      Output:           'HOSTSHORTSTATE' => 'UP',
2018-01-05 10:14:37      Output:           'SERVICEPERFDATA' => '',
2018-01-05 10:14:37      Output:           'SERVICEOUTPUT_HTML' => 'UNKNOWN - check failed - please submit a crash report!',
2018-01-05 10:14:37      Output:           'HOSTURL' => '/check_mk/index.py?start_url=view.py%3Fview_name%3Dhoststatus%26host%3Dhost1',
2018-01-05 10:14:37      Output:           'HOSTOUTPUT_HTML' => 'OK - X.X.X.X: rta 0.154ms, lost 0%',
2018-01-05 10:14:37      Output:           'PARAMETER_USER' => 'nagios',
2018-01-05 10:14:37      Output:           'SERVICEPROBLEMID' => '78356',
2018-01-05 10:14:37      Output:           'SERVICEURL' => '/check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DOrama1%26service%3Locks',
2018-01-05 10:14:37      Output:           'NOTIFICATIONAUTHOR' => '',
2018-01-05 10:14:37      Output:           'CONTACTNAME' => 'fylakio',
2018-01-05 10:14:37      Output:           'SERVICECHECKCOMMAND' => 'check_mk-check',
2018-01-05 10:14:37      Output:           'MAIL_COMMAND' => 'mail -s \'$SUBJECT$\' \'$CONTACTEMAIL$\'',
2018-01-05 10:14:37      Output:           'HOSTGROUPNAMES' => 'Servers',
2018-01-05 10:14:37      Output:           'PARAMETER_SERVICE_MESSAGE' => 'SERVICE: $HOSTNAME$/$SERVICEDESC$ - $SERVICESTATE$
2018-01-05 10:14:37      Output: Plugin Output: $SERVICEOUTPUT$
2018-01-05 10:14:37      Output: Link: $SERVICEURL$
2018-01-05 10:14:37      Output: ',
2018-01-05 10:14:37      Output:           'LONGDATETIME' => 'Fri Jan 5 10:14:36 EET 2018',
2018-01-05 10:14:37      Output:           'SERVICESTATE' => 'UNKNOWN',
2018-01-05 10:14:37      Output:           'CONTACTEMAIL' => '',
2018-01-05 10:14:37      Output:           'LASTSERVICESTATE' => 'OK',
2018-01-05 10:14:37      Output:           'HOSTACKCOMMENT' => '',
2018-01-05 10:14:37      Output:           'HOSTFORURL' => 'server1',
2018-01-05 10:14:37      Output:           'HOSTTAGS' => '/wato/parents/windows/orama_servers/ cmk-agent critical ip-v4 ip-v4-only lan site:site tcp wato',
2018-01-05 10:14:37      Output:           'LASTHOSTSTATEID' => '0',
2018-01-05 10:14:37      Output:           'SERVICENOTIFICATIONNUMBER' => '1',
2018-01-05 10:14:37      Output:           'LONGHOSTOUTPUT' => '',
2018-01-05 10:14:37      Output:           'SVC_SL' => '$_SERVICEEC_SL$',
2018-01-05 10:14:37      Output:           'PREVIOUSSERVICEHARDSHORTSTATE' => 'OK',
2018-01-05 10:14:37      Output:           'CONTACTPAGER' => '',
2018-01-05 10:14:37      Output:           'HOST_ADDRESS_FAMILY' => '4',
2018-01-05 10:14:37      Output:           'PARAMETER_XMPPSERVER' => 'X.X.X.X',
2018-01-05 10:14:37      Output:           'WHAT' => 'SERVICE',
2018-01-05 10:14:37      Output:           'HOSTSTATE' => 'UP',
2018-01-05 10:14:37      Output:           'LASTSERVICESHORTSTATE' => 'OK',
2018-01-05 10:14:37      Output:           'HOST_SL' => '$_HOSTEC_SL$',
2018-01-05 10:14:37      Output:           'SERVICESTATEID' => '3',
2018-01-05 10:14:37      Output:           'HOSTSTATEID' => '0',
2018-01-05 10:14:37      Output:           'PREVIOUSHOSTHARDSTATE' => 'UP',
2018-01-05 10:14:37      Output:           'SERVICESHORTSTATE' => 'UNKN',
2018-01-05 10:14:37      Output:           'HOST_EC_CONTACT' => '$_HOSTEC_CONTACT$',
2018-01-05 10:14:37      Output:           'HOSTDOWNTIME' => '0',
2018-01-05 10:14:37      Output:           'LASTSERVICESTATEID' => '0',
2018-01-05 10:14:37      Output:           'PARAMETER_DEBUG' => 'yes',
2018-01-05 10:14:37      Output:           'LASTHOSTSTATE' => 'UP',
2018-01-05 10:14:37      Output:           'LASTHOSTUP' => '1515140052',
2018-01-05 10:14:37      Output:           'NOTIFICATIONTYPE' => 'PROBLEM',
2018-01-05 10:14:37      Output:           'OMD_SITE' => 'site',
2018-01-05 10:14:37      Output:           'LASTHOSTSTATECHANGE_REL' => '41d 02:48:42',
2018-01-05 10:14:37      Output:           'CONTACTALIAS' => 'Fylakio',
2018-01-05 10:14:37      Output:           'LASTSERVICESTATECHANGE' => '1515140076',
2018-01-05 10:14:37      Output:           'CONTACT_XMPP' => 'user@server.example.com',
2018-01-05 10:14:37      Output:           'LASTHOSTSTATECHANGE' => '1511587555',
2018-01-05 10:14:37      Output:           'LASTHOSTSHORTSTATE' => 'UP',
2018-01-05 10:14:37      Output:           'LONGSERVICEOUTPUT_HTML' => \n',
2018-01-05 10:14:37      Output:           'SERVICEATTEMPT' => '1',
2018-01-05 10:14:37      Output:           'HOSTALIAS' => 'Server1',
2018-01-05 10:14:37      Output:           'SERVICE_EC_CONTACT' => '$_SERVICEEC_CONTACT$',
2018-01-05 10:14:37      Output:           'NOTIFICATIONAUTHORNAME' => '',
2018-01-05 10:14:37      Output:           'HOSTACKAUTHOR' => '',
2018-01-05 10:14:37      Output:           'SERVICEACKCOMMENT' => '',
2018-01-05 10:14:37      Output:           'OMD_ROOT' => '/omd/sites/site',
2018-01-05 10:14:37      Output:           'PARAMETER_HOST_MESSAGE' => 'HOST: $HOSTNAME$ - $HOSTSTATE$
2018-01-05 10:14:37      Output: Plugin Output: $HOSTOUTPUT$
2018-01-05 10:14:37      Output: Link: $HOSTURL$
2018-01-05 10:14:37      Output: ',
2018-01-05 10:14:37      Output:           'MONITORING_HOST' => 'monitor'
2018-01-05 10:14:37      Output:         };
2018-01-05 10:14:37      Output: D-main: setting Timout for the notification handler - 3s at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 209.
2018-01-05 10:14:37      Output: D-substiture_context: substitute the following string: 'SERVICE: $HOSTNAME$/$SERVICEDESC$ - $SERVICESTATE$
2018-01-05 10:14:37      Output: Plugin Output: $SERVICEOUTPUT$
2018-01-05 10:14:37      Output: Link: $SERVICEURL$
2018-01-05 10:14:37      Output: ' at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 29.
2018-01-05 10:14:37      Output: D-substiture_context: to: 'SERVICE: service - UNKNOWN
2018-01-05 10:14:37      Output: Plugin Output: UNKNOWN - check failed - please submit a crash report!
2018-01-05 10:14:37      Output: Link: /check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DOrama1%26service%3Locks
2018-01-05 10:14:37      Output: ' at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 53.
2018-01-05 10:14:37      Output: D-substiture_context: substitute the following string: 'SERVICE: $HOSTNAME$/$SERVICEDESC$ - $SERVICESTATE$
2018-01-05 10:14:37      Output: Plugin Output: $SERVICEOUTPUT$
2018-01-05 10:14:37      Output: Link: $SERVICEURL$
2018-01-05 10:14:37      Output: ' at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 29.
2018-01-05 10:14:37      Output: D-substiture_context: to: 'SERVICE: <b>service1</b>/<b>ORA ORAMADB1 Locks</b> - <b><span style='color: #FFE0A0;'>UNKNOWN</span></b><br/>
2018-01-05 10:14:37      Output: Plugin Output: <b><span style='color: #FFE0A0;'>UNKNOWN</span> - check failed - please submit a crash report!</b><br/>
2018-01-05 10:14:37      Output: Link: <b>/check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3Locks</b><br/>
2018-01-05 10:14:37      Output: ' at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 53.
2018-01-05 10:14:37      Output: D-main: constructed the following message to be sent:
2018-01-05 10:14:37      Output:  <active xmlns='http://jabber.org/protocol/chatstates'/>
2018-01-05 10:14:37      Output: <body>SERVICE: service1 - UNKNOWN
2018-01-05 10:14:37      Output: Plugin Output: UNKNOWN - check failed - please submit a crash report!
2018-01-05 10:14:37      Output: Link: /check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3Locks
2018-01-05 10:14:37      Output: </body>
2018-01-05 10:14:37      Output: <html xmlns='http://jabber.org/protocol/xhtml-im'>
2018-01-05 10:14:37      Output: <body xmlns='http://www.w3.org/1999/xhtml'>
2018-01-05 10:14:37      Output: <p>
2018-01-05 10:14:37      Output: SERVICE: <b>Orama1</b>/<b> Locks</b> - <b><span style='color: #FFE0A0;'>UNKNOWN</span></b><br/>
2018-01-05 10:14:37      Output: Plugin Output: <b><span style='color: #FFE0A0;'>UNKNOWN</span> - check failed - please submit a crash report!</b><br/>
2018-01-05 10:14:37      Output: Link: <b>/check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3%26service%20%20Locks</b><br/>
2018-01-05 10:14:37      Output: </p>
2018-01-05 10:14:37      Output: </body>
2018-01-05 10:14:37      Output: </html> at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 231.
2018-01-05 10:14:37      Output: Argument "yes" isn't numeric in numeric ge (>=) at /usr/local/share/perl/5.18.2/Net/XMPP/Debug.pm line 205.
2018-01-05 10:14:37      Output: D-xmpp_login: loging in with this arguments:
2018-01-05 10:14:37      Output: $VAR1 = {
2018-01-05 10:14:37      Output:           'ssl_verify' => 0,
2018-01-05 10:14:37      Output:           'srv' => 1,
2018-01-05 10:14:37      Output:           'connectiontype' => 'tcpip',
2018-01-05 10:14:37      Output:           'componentname' => 'site',
2018-01-05 10:14:37      Output:           'hostname' => 'X.X.X.X',
2018-01-05 10:14:37      Output:           'port' => 5222
2018-01-05 10:14:37      Output:         };
2018-01-05 10:14:37      Output: D-xmpp_check_result: Connect: 1 at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 94.
2018-01-05 10:14:37      Output: D-xmpp_check_result: AuthSend: ok at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 94.
2018-01-05 10:14:38      Output: Disconnect. at /omd/sites/site/local/share/check_mk/notifications/xmpp.pl line 116.`

**Comment by grego1981** [comment]
And this the error in OpenFire server 4.2.1 

2018.01.05 10:26:34 ERROR [socket_c2s-thread-3]: org.jivesoftware.openfire.nio.ConnectionHandler - Closing connection due to error while processing message: <message to='gtsintaris@server.example.com' type='message'><active xmlns='http://jabber.org/protocol/chatstates'/>


Which means the message goes to the server but for some reason it gets rejected...

**Comment by seppovic** [comment]
Hey Hey, thx for your feedback, i know the plugin is quite crappy. i cant test or verify your problem atm but i will look into it when i am back @work.

**Comment by seppovic** [comment]
Hey gregor, can you test commit 97135bd91056e3693cad561049a298cdacc1a992

**Comment by grego1981** [comment]
Hi @seppovic !

I'll try it out as soon as possible and gine you feedback.

Thank you!
Gregory

**Comment by grego1981** [comment]
Goodmorning!

The messages in the logs, have changed, the notification reaches the server like before, but I get the following in the all.log.
The weird thing is that I'm logged in as this user gtsintaris@itsrv-02.central2.local and I can send xmpp message trhough the same same server, from the monitoring server using the sendxmpp utility....


2018.01.23 08:15:47 DEBUG [socket_c2s-thread-4]: org.jivesoftware.openfire.spi.RoutingTableImpl - Failed to route packet to JID: gtsintaris@itsrv-02.central2.local packet: <message to="gtsintaris@itsrv-02.central2.local" type="message" from="nagios@itsrv-02.central2.local/magoula"><active xmlns="http://jabber.org/protocol/chatstates"></active>
<body>SERVICE: MGMKRTR/Mikrotik-Wind BW - WARNING
Plugin Output: WARNING - Bandwidth usage is 3169.200000 kbps - Rx/Tx=2700.000000/469.2 kbps - %Usage Tx/Rx/Overall = 11.730000%/67.500000%/79.225000%
Link: /check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DMGMKRTR%26service%3DMikrotik-Wind%20BW
</body>
<html xmlns="http://jabber.org/protocol/xhtml-im">
<body xmlns="http://www.w3.org/1999/xhtml">
<p>
SERVICE: <b>MGMKRTR</b>/<b>Mikrotik-Wind BW</b> - <b><span style="color: #FFFFAA;">WARNING</span></b><br/>
Plugin Output: <b><span style="color: #FFFFAA;">WARNING</span> - Bandwidth usage is 3169.200000 kbps - Rx/Tx=2700.000000/469.2 kbps - %Usage Tx/Rx/Overall = 11.730000%/67.500000%/79.225000%</b><br/>
Link: <b>/check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DMGMKRTR%26service%3DMikrotik-Wind%20BW</b><br/>
</p>
</body>
</html></message>
2018.01.23 08:15:47 DEBUG [socket_c2s-thread-4]: org.jivesoftware.openfire.MessageRouter - Message sent to unreachable address: <message to="gtsintaris@itsrv-02.central2.local" type="message" from="nagios@itsrv-02.central2.local/magoula"><active xmlns="http://jabber.org/protocol/chatstates"></active>
<body>SERVICE: MGMKRTR/Mikrotik-Wind BW - WARNING
Plugin Output: WARNING - Bandwidth usage is 3169.200000 kbps - Rx/Tx=2700.000000/469.2 kbps - %Usage Tx/Rx/Overall = 11.730000%/67.500000%/79.225000%
Link: /check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DMGMKRTR%26service%3DMikrotik-Wind%20BW
</body>
<html xmlns="http://jabber.org/protocol/xhtml-im">
<body xmlns="http://www.w3.org/1999/xhtml">
<p>
SERVICE: <b>MGMKRTR</b>/<b>Mikrotik-Wind BW</b> - <b><span style="color: #FFFFAA;">WARNING</span></b><br/>
Plugin Output: <b><span style="color: #FFFFAA;">WARNING</span> - Bandwidth usage is 3169.200000 kbps - Rx/Tx=2700.000000/469.2 kbps - %Usage Tx/Rx/Overall = 11.730000%/67.500000%/79.225000%</b><br/>
Link: <b>/check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DMGMKRTR%26service%3DMikrotik-Wind%20BW</b><br/>
</p>
</body>
</html></message>
2018.01.23 08:15:47 ERROR [socket_c2s-thread-4]: org.jivesoftware.openfire.MessageRouter - Failed to route packet: <message to="gtsintaris@itsrv-02.central2.local" type="message" from="nagios@itsrv-02.central2.local/magoula"><active xmlns="http://jabber.org/protocol/chatstates"></active>
<body>SERVICE: MGMKRTR/Mikrotik-Wind BW - WARNING
Plugin Output: WARNING - Bandwidth usage is 3169.200000 kbps - Rx/Tx=2700.000000/469.2 kbps - %Usage Tx/Rx/Overall = 11.730000%/67.500000%/79.225000%
Link: /check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DMGMKRTR%26service%3DMikrotik-Wind%20BW
</body>
<html xmlns="http://jabber.org/protocol/xhtml-im">
<body xmlns="http://www.w3.org/1999/xhtml">
<p>
SERVICE: <b>MGMKRTR</b>/<b>Mikrotik-Wind BW</b> - <b><span style="color: #FFFFAA;">WARNING</span></b><br/>
Plugin Output: <b><span style="color: #FFFFAA;">WARNING</span> - Bandwidth usage is 3169.200000 kbps - Rx/Tx=2700.000000/469.2 kbps - %Usage Tx/Rx/Overall = 11.730000%/67.500000%/79.225000%</b><br/>
Link: <b>/check_mk/index.py?start_url=view.py%3Fview_name%3Dservice%26host%3DMGMKRTR%26service%3DMikrotik-Wind%20BW</b><br/>
</p>
</body>
</html></message>
java.lang.IllegalArgumentException: No enum constant org.xmpp.packet.Message.Type.message
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.xmpp.packet.Message$Type.valueOf(Message.java:284)
	at org.xmpp.packet.Message.getType(Message.java:98)
	at org.jivesoftware.openfire.MessageRouter.routingFailed(MessageRouter.java:252)
	at org.jivesoftware.openfire.spi.RoutingTableImpl.routePacket(RoutingTableImpl.java:270)
	at org.jivesoftware.openfire.MessageRouter.route(MessageRouter.java:134)
	at org.jivesoftware.openfire.spi.PacketRouterImpl.route(PacketRouterImpl.java:79)
	at org.jivesoftware.openfire.net.StanzaHandler.processMessage(StanzaHandler.java:379)
	at org.jivesoftware.openfire.net.ClientStanzaHandler.processMessage(ClientStanzaHandler.java:109)
	at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:233)
	at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:200)
	at org.jivesoftware.openfire.nio.ConnectionHandler.messageReceived(ConnectionHandler.java:177)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:769)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:761)
	at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:703)
	at java.lang.Thread.run(Thread.java:748)

**Comment by seppovic** [comment]
hm, hard to tell from here, a few places you could look into:
gtsintaris@itsrv-02.central2.local is the value in CONTACT_XMPP custom attribut of the user to notify?
The JID you configured in WATO Notifications rule can log into the xmpp server? the checkbox "Reciepient is a chatroom" is not checked?

**Comment by grego1981** [comment]
Yes this is the value (you can see it on first pisture)

And on the second one you can see the config in the notifications rule

![user_contact](https://user-images.githubusercontent.com/9021998/35374828-32965a8a-01ad-11e8-9a29-8f9caf4249ac.PNG)
![notifs](https://user-images.githubusercontent.com/9021998/35374830-35a6d0ec-01ad-11e8-88df-58d0224dd6e1.PNG)
